name: PHP Quality Checks & Deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHP Syntax Check
      run: find . -type f -name '*.php' ! -path './vendor/*' -exec php -l {} \;

    - name: Run Composer Security Audit
      run: composer audit

    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit tests/

  # СЕКЦИЯ ЗА АВТОМАТИЧНО КАЧВАНЕ
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    # Тук генерираме папката vendor
    - name: Build Production Vendor Folder
      run: composer install --no-dev --optimize-autoloader

    # Изпращаме файловете към InfinityFree
    - name: FTP Deploy to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/tests/**
          phpunit.xml
